version: '3'
services:
    upngo:
        build:
            context: .
            dockerfile: Dockerfile-upngo
        image: "alarsyo/upngo"
        restart: always
        networks:
            - upngo-net
    caddy:
        build:
            context: .
            dockerfile: Dockerfile-caddy
        image: "alarsyo/caddy"
        restart: always
        ports:
            - "80:80"
            - "443:443"
        networks:
            - upngo-net
        depends_on:
            - upngo
        volumes:
            - "$HOME/.caddy:/root/.caddy"
        environment:
            - UPNGO_HOSTNAME

networks:
    upngo-net:
